//! Regression test over vectors generated by `tests/generate-parity-vectors.mjs`.
//! The fixture contains the exact record bytes emitted by the JS canonical encoder and the verdict
//! computed by the JS claim type. Keeping it in the repository makes JS↔Rust consensus drift fail
//! in `cargo test`, rather than only in a one-off audit harness.

use super::{cmls, solvency, Fold, CHUNK_RECORDS};

const VECTORS: &str = include_str!("../../../../tests/parity-vectors.txt");

fn decode_hex(s: &str) -> Vec<u8> {
    assert_eq!(s.len() % 2, 0, "hex vector must have an even length");
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).expect("fixture contains valid hex"))
        .collect()
}

#[test]
fn js_generated_canonical_vectors_match_rust_reexecution() {
    let mut vectors = 0usize;
    for (line_no, line) in VECTORS.lines().enumerate() {
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let fields: Vec<_> = line.split('|').collect();
        assert_eq!(fields.len(), 4, "invalid parity vector at line {}", line_no + 1);
        let expected = fields[2].parse::<u8>().expect("fixture contains a flag id");
        let bytes = decode_hex(fields[3]);
        let mut fold = Fold::default();
        let actual = match fields[0] {
            "CMLS" => {
                let chunk_len = cmls::RECORD_SIZE * CHUNK_RECORDS as usize;
                for chunk in bytes.chunks(chunk_len) {
                    cmls::fold_chunk(&mut fold, chunk).expect("JS CMLS bytes must fold in Rust");
                }
                if fields[1] == "multi-chunk-201" {
                    assert_eq!(bytes.len(), cmls::RECORD_SIZE * 201);
                    assert_eq!(fold.count, 201);
                }
                cmls::verdict(&fold)
            }
            "SOLVENCY" => {
                solvency::fold_chunk(&mut fold, &bytes).expect("JS solvency bytes must fold in Rust");
                solvency::verdict(&fold)
            }
            other => panic!("unknown parity vector kind {other}"),
        };
        assert_eq!(actual, expected, "parity mismatch for {}", fields[1]);
        vectors += 1;
    }
    assert_eq!(vectors, 160, "fixture coverage changed unexpectedly");
}
